version: '3.8'

services: 
  cuttlefish:
    build: ./cuttlefish
    ports:
      - "5000:5000"
    volumes:
      - ./cuttlefish:/app
    depends_on:
      - sediment
  sediment:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./initial/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: filefish
      POSTGRES_PASSWORD: filefish
      POSTGRES_DB: sediment
    ports:
      - 5432:5432

      
volumes:
  postgres_data: