# Use an official Python runtime as a parent image
FROM python:3.10.7-slim-buster

# Set the working directory in the container to /app
WORKDIR /app


# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip pipenv 
COPY Pipfile* ./

RUN pipenv install --system --ignore-pipfile

# copy projectd
COPY . /app


# Run app.py when the container launches
ENTRYPOINT ["sh", "entrypoint.sh"]
CMD ["python", "app.py"]
